<?php

namespace NIBundle\Repository;

/**
 * DangerRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DangerRepository extends \Doctrine\ORM\EntityRepository
{
}
