<?php

namespace NIBundle\Repository;

/**
 * TypeDangerRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TypeDangerRepository extends \Doctrine\ORM\EntityRepository
{
}
